### ISSUE TITLE
레이블 관리 페이지

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#13]
레이블만을 관리하기 위한 페이지 

탭을 레이블 타입만큼 만들어주어야 함 각 타입 4개 

페이지네이션 없음

**Comment by LaziesFirst** [comment]
@dbaudwns20 다른 셀 눌렀을 때 편집 안풀리는거 고치기

**Comment by dbaudwns20** [comment]
## 텝 [전체, 사용자, 클래스, 시험, 과제]
- 전체 텝에선 레이블 생성 버튼이 보이지 않음
- 활성화 된 탭에서 [신규] 버튼으로 생성하면 해당 탭의 레이블이 생성 됨
- 신규 행은 제한은 1개
- 체크박스를 선택하면 일괄 삭제버튼 보임
## 다음 상황일때 편집 중인 내용은 초기화 됨
- [취소] 클릭 시
- 다른 행 클릭 시
- 다른 행 [편집] 버튼을 클릭 시
- [신규] 버튼을 눌렀을 시
- 엔터키를 눌렀을 시 -> 현재 편집 중인 셀이라면 저장 프로세스를 태우고 싶은데 쉽지않음...
