### ISSUE TITLE
레이블 드랍다운 모달

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#14]
예를 들어 사용자에 붙이는 레이블은 자동으로 사용자 레이블을 요청해야하고 나머지 클래스, 테스트 등 오브젝트가 뭔지에 따라 해당 레이블 호출해서 작게 드랍다운 띄워주는 UI

**Comment by dbaudwns20** [comment]
<img width="315" alt="스크린샷 2023-02-16 오후 3 22 51" src="https://user-images.githubusercontent.com/33855022/219285091-82424515-988b-44e3-9c50-bc784a370ea8.png">

다음과 같이 구현 완료

화살표 위, 아래, 엔터키 입력 시 선택되는 기능 추가 예정

**Comment by dbaudwns20** [comment]
<img width="706" alt="스크린샷 2023-02-27 오후 5 48 28" src="https://user-images.githubusercontent.com/33855022/221516492-205a991a-ca7d-42dc-b1b0-891bca9e5010.png">

- 화살표 위, 아래: focus 된 레이블 이동 첫번째 레이블에서 윗버튼으로 이동 시 리스트 목록 닫힘.
- 엔터: 선택 or 해제
- 백스페이스 (지우기): 선택된 레이블 지우기 가능
- esc:  리스트 목록 닫힘.
- 다중 선택으로 저장되도록 개선
