### ISSUE TITLE
레이블 생성

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#15]
이름 색상 필수
설명 선택

색상은 무작위로 헥스코드 생성해주는 기능 있었으면 좋겠음 + 컬러픽커

**Comment by dbaudwns20** [comment]
[신규] 버튼 클릭 시 무작위 헥스 코드로 생성되도록 구현, 신규 행은 1개 밖에 추가되지 않음
텍스트, 컬러코드 값 중 하나라도 값이 비어있다면 저장버튼 비활성화
