### ISSUE TITLE
레이블 수정 삭제

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#16]
깃헙을 참고해서 레이블 관리 페이지에서는 단일 수정, 단일 삭제가 가능하도록
다중은 지원하지 않음

**Comment by dbaudwns20** [comment]
레이블 기능 추가 완료 
- 단일 편집, 삭제
- 다중 삭제 (삭제버튼은 체크박스가 선택되어야 보여짐)
