### ISSUE TITLE
레이블 테이블 디테일

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#26]
- [x] 취소, 삭제 등 버튼 색상이 너무 많다는 생각이 들어서 아이콘으로 처리하면 색상 고민 하지 않아도 되고 직관적으로 사용자에게 인식될 수 있을 것 같음
- [x] 컬러코드나 레이블 이름 변경했을 때 바로바로 반영되도록 만들기
- [ ] 테이블 컬럼에 컬러 코드가 보일 필요가 없을 것 같음(레이블 색상을 보고 인식할 수 있으니까) 편집을 시도할 때만 컬러 코드 생성기 보여주기

**Comment by dbaudwns20** [comment]
취소, 삭제 등 버튼 색상이 너무 많다는 생각이 들어서 아이콘으로 처리하면 색상 고민 하지 않아도 되고 직관적으로 사용자에게 인식될 수 있을 것 같음
- **생성 (초록색), 편집 (파란색), 삭제 (빨간색), 취소 (회색) 으로 처리**

컬러코드나 레이블 이름 변경했을 때 바로바로 반영되도록 만들기
- **변경 시 바로 반영되도록 수정 완료**

테이블 컬럼에 컬러 코드가 보일 필요가 없을 것 같음(레이블 색상을 보고 인식할 수 있으니까) 편집을 시도할 때만 컬러 코드 생성기 보여주기
- **가능은 한데 그리드 특성상 한 행이 편집을 누르면 나머지 행도 다 보이게 됨. 이게 의미가 있나?**
<img width="952" alt="스크린샷 2023-02-07 오후 5 25 57" src="https://user-images.githubusercontent.com/33855022/217191451-d3d6db8b-2c08-4033-82e4-998240ea377b.png">

<img width="939" alt="스크린샷 2023-02-07 오후 5 26 02" src="https://user-images.githubusercontent.com/33855022/217191464-c7a3f8c5-ba53-42b4-8a54-48f3d6389ecc.png">

**Comment by dbaudwns20** [comment]
3번째 항목은 회의때 구현 하지 않도록 협의
