### ISSUE TITLE
부모 계정 아이디 중복 체크

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#38]
ParentDuplication

**Comment by dbaudwns20** [comment]
Username 컴포넌트에 props 추가
null 이면 사용안함, 'user' : 사용자, 'parent' : 부모님

<img width="484" alt="스크린샷 2023-02-27 오후 5 43 00" src="https://user-images.githubusercontent.com/33855022/221515490-5e0e42a6-a40d-4df4-b1fe-887e1fc2f033.png">

dupCheckTarget 값으로 API 호출 분기 처리
<img width="781" alt="스크린샷 2023-02-27 오후 5 42 50" src="https://user-images.githubusercontent.com/33855022/221515628-592e7477-e6ee-43fb-867e-0ff55371245e.png">

적용완료
