### ISSUE TITLE
디테일 그리드

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#42]
지금은 이렇게 쭉 나열되어 있는데 

<img width="1312" alt="스크린샷 2023-02-28 오전 4 29 06" src="https://user-images.githubusercontent.com/62410444/221854467-81fdfcfd-17a7-400a-8720-9c921367996d.png">

에디터 모달처럼 세로로 길게 하는게 어떨지

<img width="631" alt="스크린샷 2023-02-28 오전 4 30 02" src="https://user-images.githubusercontent.com/62410444/221854617-86a24554-676b-4db3-aaf0-8f4f31286a33.png">

**Comment by LaziesFirst** [comment]
다른 디테일 그리드 펼쳤을 때 이전에 열어둔 디테일 안닫힘

**Comment by LaziesFirst** [comment]
row 를 더블 클릭해야지 펼쳐지는데 마우스 올렸을 때 마우스오버(손가락) 되면서 한번 클릭했을 때 펼쳐지도록 하는게 좋을 것 같음

**Comment by LaziesFirst** [comment]
정렬 버그 및 순번 버그
디테일 연 상태에서 컬럼 정렬 하면 이상해짐 

<img width="1381" alt="스크린샷 2023-02-28 오전 4 44 16" src="https://user-images.githubusercontent.com/62410444/221858042-18f9b22d-9b01-43a1-bd81-5f71056cc57b.png">

- 디테일 그리드 포기하거나 -> 모달
- 라이브러리에서 지원하는 컬럼 정렬을 막고 원하는 정렬 리퀘스트를 통해서 정렬했을때 제대로 동작하도록 하거나(추후 개발)
- 정렬 이벤트 발생시 열려있는 디테일 닫거나

**Comment by dbaudwns20** [comment]
- 다른 디테일 그리드 펼쳤을 때 이전에 열어둔 디테일 안닫힘
  > 한눈에 보기 위함이라서 유지시킨건데. 만일 첫번째 코멘트처럼 세로로 길게 보일거면 다른 디테일은 숨기는게 맞아보임

- row 를 더블 클릭해야지 펼쳐지는데 마우스 올렸을 때 마우스오버(손가락) 되면서 한번 클릭했을 때 펼쳐지도록 하는게 좋을 것 같음
  > 잘못클릭 방지임. 맨 왼쪽에 화살표 버튼은 한번만 클릭하면 됨

- 정렬 버그 및 순번 버그
  > 정렬은 api 호출로 구현할 예정이고. 호출하면 그리드 리스트가 새로 그려지기 때문에 디테일은 닫힐거임

**Comment by dbaudwns20** [comment]
디테일 ui 변경

<img width="1340" alt="스크린샷 2023-03-06 오후 5 33 47" src="https://user-images.githubusercontent.com/33855022/223058030-b66c8eee-ae4b-4e17-b25b-d85ab27ee591.png">

편집버튼을 누르면 disabled 영역이 활성화되고 저장 버튼을 누르면 API 호출, 취소를 누르면 변경 데이터 롤백
