### ISSUE TITLE
모달은 히스토리로 잡히지 않아야 함

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#46]
`localhost:8080/#/user/create-parent` 를 연 다음 닫으면 뒤로가기가 가능해지는데 모달이 뒤로가기에 잡히지 않도록

모달이 url을 가지기 때문에 이게 가능한가? 싶음

**Comment by dbaudwns20** [comment]
모달 닫히면 모달 히스토리를 지우는 방식 찾아보기

**Comment by dbaudwns20** [comment]
[https://stackoverflow.com/a/71155305/21115794](url)

불가능
