### ISSUE TITLE
클래스 생성 기능

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#54]
클래스 생성 종류는 두개

관리자 계정 이상부터는 본인을 클래스의 관리자로 지정하면서 클래스를 생성하는 기능과 본인을 관리자로 지정하지 않으면서 클래스를 생성하는 기능 두가지가 있음

관리자 계정 이상부터는 자신이 관리자가 아닌 클래스도 조회할 수 있기 떄문

교사 계정은 본인을 관리자로 지정하면서 클래스를 생성하는 기능밖에 없음

클래스는 이름 이외에 기본값이 지정되기 때문에 이름만 빈칸인지 검사함

- 시작날짜 미지정시 현재
- 종료날짜 미지정시 한달 뒤
- 공개여부날짜는 null이면 미공개, null이 아니라 빈값으로라도 지정하면 현재로 지정

**Comment by LaziesFirst** [comment]
이름 중복은 상관없음

**Comment by LaziesFirst** [comment]
추가로 선생 권한 이상의 사용자들을 클래스 관리자로 설정해서 생성하는 기능도 개발 필요, 당연히 추후에 관리자를 수정하는 기능도 있어야 함

클래스를 생성할 때는 관리자만 설정할 수 있음 참여 학생은 레이블 설정과 마찬가지로 생성과 동시에 하지 않고 참여 학생 수정 페이지에서 구현

한 페이지에서 여러 요청을 처리하면 서버&클라이언트 복잡성이 증가함 그리고 크게 불편하지 않을 것으로 생각됨

필요사항은 레이블 선택 드랍다운처럼 관리자를 지정하기 위해서 사용자 선택 드랍다운 필요

**Comment by LaziesFirst** [comment]
추가로 선생 권한 이상의 사용자들을 클래스 관리자로 설정해서 생성하는 기능도 개발 필요, 당연히 추후에 관리자를 수정하는 기능도 있어야 함

클래스를 생성할 때는 관리자만 설정할 수 있음 참여 학생은 레이블 설정과 마찬가지로 생성과 동시에 하지 않고 참여 학생 수정 페이지에서 구현

한 페이지에서 여러 요청을 처리하면 서버&클라이언트 복잡성이 증가함 그리고 크게 불편하지 않을 것으로 생각됨

필요사항은 레이블 선택 드랍다운처럼 관리자를 지정하기 위해서 사용자 선택 드랍다운 필요

**Comment by dbaudwns20** [comment]
![스크린샷 2023-03-26 오전 12 27 16](https://user-images.githubusercontent.com/33855022/227726668-4a38dffc-f3dc-40eb-9fb4-8b0b6e3774de.png)

클래스 신규 구현 완료

선생권한 이상부터 생성 가능하며 관리자권한 이상부터 담당자 지정을 본인, 미지정 선택 가능, 선생 권한은 무조건 본인이 주담당자로 지정됨
