### ISSUE TITLE
프로필 가져오기

### ISSUE THREAD

**Issue by LaziesFirst** [dbaudwns20/jisaem-client#9]
자기 프로필 가져오기 
프로필 가져와서 UI 표출

**Comment by dbaudwns20** [comment]
<img width="1375" alt="스크린샷 2023-01-29 오후 3 37 23" src="https://user-images.githubusercontent.com/33855022/215309554-149804e4-7655-4c97-97e1-71e4fa956d9a.png">
프로필 페이지 이동 시 개인정보 표출

** 근데 student_info 정보는 어디서 보일건데? **

**Comment by LaziesFirst** [comment]
학생 로그인 시 student_info 가 있을 수도 있고 없을 수도 있음
- 있는 경우 학교명만 표시
- 없는 경우 학교명 필드는 있지만 값을 비워둠

**Comment by LaziesFirst** [comment]
부모 로그인 시 보여지는 필드는 학생과 동일하지만 모든 필드를 수정할 수 없음

+ 아이디 란에 student_info.parent_username 을 보여줘야 하고 비밀번호 변경은 토큰 권한에 따라 서버에서 처리하므로 따로 분기 없이 passwordUpdate 호출하면 됨

**Comment by dbaudwns20** [comment]
로그인한 권한 별로 프로필 수정할 수 있도록 개선 완료
